import os
import uuid
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# --- HINDI FONT REGISTRATION ---
# Search for standard Devanagari fonts on Windows to support Hindi PDFs
HINDI_FONT_NAME = "Helvetica"
HINDI_FONT_BOLD_NAME = "Helvetica-Bold"
FONT_REGISTERED = False

hindi_fonts = [
    ("Mangal", "mangal.ttf", "mangalb.ttf"),
    ("Nirmala", "Nirmala.ttf", "NirmalaB.ttf"),
    ("Utsaah", "utsaah.ttf", "utsaahb.ttf"),
    ("Aparajita", "aparaj.ttf", "aparajb.ttf"),
]

for name, regular, bold in hindi_fonts:
    reg_path = os.path.join("C:\\Windows\\Fonts", regular)
    bold_path = os.path.join("C:\\Windows\\Fonts", bold)
    if os.path.exists(reg_path):
        try:
            pdfmetrics.registerFont(TTFont(name, reg_path))
            if os.path.exists(bold_path):
                pdfmetrics.registerFont(TTFont(f"{name}-Bold", bold_path))
                HINDI_FONT_BOLD_NAME = f"{name}-Bold"
            else:
                HINDI_FONT_BOLD_NAME = name
            HINDI_FONT_NAME = name
            FONT_REGISTERED = True
            break
        except Exception:
            pass

# --- CUSTOM TWO-PASS CANVAS FOR PAGE NUMBERS ---
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # 1. HEADER (Only if page > 1 or on all pages since we want branding)
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#1A56DB"))
        self.drawString(56.7, 841.89 - 36, "MEDASSIST AI")
        
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawRightString(595.27 - 56.7, 841.89 - 36, "Symptom Assessment Report")
        
        # Header line
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(56.7, 841.89 - 42, 595.27 - 56.7, 841.89 - 42)
        
        # 2. FOOTER
        # Footer line
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(56.7, 48, 595.27 - 56.7, 48)
        
        # Footer text
        self.setFont("Helvetica", 7.5)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(56.7, 34, "Disclaimer: Generated by MedAssist AI. Informational purposes only. Not a substitute for professional medical advice.")
        
        # Page numbers
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.setFont("Helvetica-Bold", 8)
        self.drawRightString(595.27 - 56.7, 34, page_text)
        
        self.restoreState()

class PDFService:
    @staticmethod
    def generate_report_pdf(report_data: dict, input_data: dict) -> BytesIO:
        buffer = BytesIO()
        
        # Page size A4: 595.27 x 841.89 points
        # 2cm margins = ~56.7 points
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=56.7,
            rightMargin=56.7,
            topMargin=56.7,
            bottomMargin=56.7
        )
        
        language = input_data.get("language", "en")
        font_reg, font_bold = "Helvetica", "Helvetica-Bold"
        if language == "hi" and FONT_REGISTERED:
            font_reg = HINDI_FONT_NAME
            font_bold = HINDI_FONT_BOLD_NAME
            
        # Dynamically map labels to avoid missing Devanagari font glyph blocks in English PDFs
        if language == "hi":
            lbl = {
                "name": "रोगी का नाम:",
                "report_id": "रिपोर्ट आईडी:",
                "generated": "उत्पन्न तिथि:",
                "age": "आयु:",
                "sex": "लिंग:",
                "symptoms": "लक्षण:",
                "duration": "अवधि:",
                "meds": "दवाएं:",
                "allergies": "एलर्जी:",
                "conditions": "बीमारियां:",
                "triage_level": "तात्कालिकता स्तर:",
                "reasoning": "नैदानिक तर्क:",
                "specialist": "अनुशंसित विशेषज्ञ:",
                "diagnosis": "निदान",
                "explanation": "नैदानिक व्याख्या",
                "likelihood": "संभावना",
                "drug": "दवा",
                "dosage": "खुराक",
                "timing": "समय",
                "duration_otc": "अवधि / OTC",
                "warnings": "चेतावनी",
                "interaction": "दवाएं",
                "severity": "गंभीरता",
                "description": "विवरण",
                "allergy_alert": "एलर्जी चेतावनी:"
            }
        else:
            lbl = {
                "name": "Patient Name:",
                "report_id": "Report ID:",
                "generated": "Generated:",
                "age": "Age:",
                "sex": "Biological Sex:",
                "symptoms": "Symptoms:",
                "duration": "Duration:",
                "meds": "Current Meds:",
                "allergies": "Allergies:",
                "conditions": "Conditions:",
                "triage_level": "Triage Level:",
                "reasoning": "Clinical Reasoning:",
                "specialist": "Recommended Specialist:",
                "diagnosis": "Diagnosis",
                "explanation": "Clinical Explanation",
                "likelihood": "Likelihood",
                "drug": "Drug",
                "dosage": "Dosage / Freq",
                "timing": "Timing & Meal",
                "duration_otc": "Duration / OTC",
                "warnings": "Warnings",
                "interaction": "Interaction",
                "severity": "Severity",
                "description": "Description",
                "allergy_alert": "ALLERGY ALERT:"
            }

        styles = getSampleStyleSheet()
        
        # Custom styles to fit A4 layout cleanly
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Normal'],
            fontName=font_bold,
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#1A56DB"),
            spaceAfter=6
        )
        
        meta_label_style = ParagraphStyle(
            'MetaLabel',
            parent=styles['Normal'],
            fontName=font_bold,
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#475569")
        )
        
        meta_val_style = ParagraphStyle(
            'MetaVal',
            parent=styles['Normal'],
            fontName=font_reg,
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#0F172A")
        )
        
        sec_title_style = ParagraphStyle(
            'SectionTitle',
            parent=styles['Normal'],
            fontName=font_bold,
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#1A56DB"),
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True
        )
        
        body_style = ParagraphStyle(
            'BodyVal',
            parent=styles['Normal'],
            fontName=font_reg,
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#0F172A")
        )
        
        body_bold_style = ParagraphStyle(
            'BodyBold',
            parent=styles['Normal'],
            fontName=font_bold,
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#0F172A")
        )
        
        disclaimer_style = ParagraphStyle(
            'DisclaimerText',
            parent=styles['Normal'],
            fontName=font_reg,
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#991B1B")
        )
        
        badge_style = ParagraphStyle(
            'BadgeText',
            parent=styles['Normal'],
            fontName=font_bold,
            fontSize=8,
            leading=10,
            alignment=1, # Centered
            textColor=colors.white
        )

        story = []
        
        # --- DISCLAIMER BANNER AT TOP ---
        disclaimer_title = "<b>IMPORTANT SAFETY WARNING / महत्वपूर्ण सुरक्षा चेतावनी:</b>"
        disclaimer_body = (
            "This report is AI-generated for informational purposes only and does not constitute professional medical advice, "
            "diagnosis, or treatment. Always consult a qualified healthcare provider immediately with any medical questions. "
            "If you are experiencing a medical emergency, please contact your local emergency services (e.g. 911 or 112) or go to the nearest ER."
            if language == "en" else
            "यह रिपोर्ट केवल सूचनात्मक उद्देश्यों के लिए AI द्वारा उत्पन्न की गई है और यह पेशेवर चिकित्सा सलाह, निदान या उपचार का गठन नहीं करती है। "
            "किसी भी चिकित्सीय प्रश्न के लिए हमेशा योग्य स्वास्थ्य सेवा प्रदाता से तुरंत परामर्श लें। यदि आप चिकित्सा आपातकाल का अनुभव कर रहे हैं, "
            "तो कृपया तुरंत स्थानीय आपातकालीन सेवाओं (जैसे 112) से संपर्क करें या निकटतम आपातकालीन विभाग में जाएं।"
        )
        
        disclaimer_data = [[
            Paragraph(f"{disclaimer_title}<br/>{disclaimer_body}", disclaimer_style)
        ]]
        disclaimer_table = Table(disclaimer_data, colWidths=[481])
        disclaimer_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FEF2F2")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#EF4444")),
            ('PADDING', (0,0), (-1,-1), 8),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(disclaimer_table)
        story.append(Spacer(1, 10))
        
        # --- HEADER SECTION ---
        # Generate clean ID and timestamp
        report_id = str(uuid.uuid4())[:8].upper()
        generated_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        header_text = "MedAssist Symptom Assessment" if language == "en" else "MedAssist लक्षण मूल्यांकन"
        story.append(Paragraph(header_text, title_style))
        
        # Metadata block
        meta_en = [
            [Paragraph(lbl["report_id"], meta_label_style), Paragraph(f"MA-{report_id}", meta_val_style),
             Paragraph(lbl["generated"], meta_label_style), Paragraph(generated_time, meta_val_style)]
        ]
        meta_table = Table(meta_en, colWidths=[80, 160, 80, 161])
        meta_table.setStyle(TableStyle([
            ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('PADDING', (0,0), (-1,-1), 4),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 10))
        
        # --- SECTION 1: PATIENT SUMMARY ---
        summary_title = "1. Patient Summary" if language == "en" else "1. रोगी का सारांश"
        story.append(Paragraph(summary_title, sec_title_style))
        
        # Prepare content
        name_val = str(input_data.get("name")) if input_data.get("name") else ("Not provided" if language == "en" else "प्रदान नहीं किया गया")
        age_val = str(input_data.get("age")) if input_data.get("age") is not None else ("Not provided" if language == "en" else "प्रदान नहीं किया गया")
        sex_val = str(input_data.get("sex")) if input_data.get("sex") is not None else ("Not provided" if language == "en" else "प्रदान नहीं किया गया")
        symptoms_val = ", ".join(input_data.get("symptoms", []))
        duration_val = str(input_data.get("duration")) if input_data.get("duration") is not None else ("Not provided" if language == "en" else "प्रदान नहीं किया गया")
        meds_val = ", ".join(input_data.get("medications", [])) if input_data.get("medications") else ("None" if language == "en" else "कोई नहीं")
        allergies_val = str(input_data.get("allergies")) if input_data.get("allergies") else ("None" if language == "en" else "कोई नहीं")
        conditions_val = ", ".join(input_data.get("conditions", [])) if input_data.get("conditions") else ("None" if language == "en" else "कोई नहीं")
        
        summary_data = [
            [Paragraph(lbl["name"], meta_label_style), Paragraph(name_val, meta_val_style),
             Paragraph(lbl["age"], meta_label_style), Paragraph(age_val, meta_val_style)],
            [Paragraph(lbl["sex"], meta_label_style), Paragraph(sex_val, meta_val_style),
             Paragraph(lbl["duration"], meta_label_style), Paragraph(duration_val, meta_val_style)],
            [Paragraph(lbl["meds"], meta_label_style), Paragraph(meds_val, meta_val_style),
             Paragraph(lbl["allergies"], meta_label_style), Paragraph(allergies_val, meta_val_style)],
            [Paragraph(lbl["conditions"], meta_label_style), Paragraph(conditions_val, meta_val_style),
             Paragraph("", meta_label_style), Paragraph("", meta_val_style)]
        ]
        
        summary_table = Table(summary_data, colWidths=[110, 130, 110, 131])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F8FAFC")),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#F1F5F9")),
            ('PADDING', (0,0), (-1,-1), 5),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 10))
        
        # --- SECTION 2: URGENCY TRIAGE BANNER ---
        urgency_title = "2. Urgency Triage Level" if language == "en" else "2. तात्कालिकता वर्गीकरण (Urgency Triage)"
        story.append(Paragraph(urgency_title, sec_title_style))
        
        urgency_info = report_data.get("urgency", {})
        urg_level = urgency_info.get("level", "Low")
        urg_reason = urgency_info.get("reasoning", "")
        urg_specialist = urgency_info.get("recommended_specialist", "")
        
        # Colors for triage
        if urg_level == "Emergency":
            bg_color, border_color, text_color = "#FEE2E2", "#DC2626", "#991B1B"
        elif urg_level == "High":
            bg_color, border_color, text_color = "#FFEDD5", "#EA580C", "#9A3412"
        elif urg_level == "Moderate":
            bg_color, border_color, text_color = "#FEF9C3", "#CA8A04", "#854D0E"
        else: # Low
            bg_color, border_color, text_color = "#DCFCE7", "#16A34A", "#166534"
            
        triage_label_style = ParagraphStyle(
            'TriageLabel', parent=styles['Normal'],
            fontName=font_bold, fontSize=11, leading=14, textColor=colors.HexColor(text_color)
        )
        triage_val_style = ParagraphStyle(
            'TriageVal', parent=styles['Normal'],
            fontName=font_reg, fontSize=9, leading=13, textColor=colors.HexColor(text_color)
        )
        
        triage_data = [
            [Paragraph(f"{lbl['triage_level']} <b>{urg_level.upper()}</b>", triage_label_style)],
            [Paragraph(f"<b>{lbl['reasoning']}</b> {urg_reason}", triage_val_style)],
            [Paragraph(f"<b>{lbl['specialist']}</b> {urg_specialist}", triage_val_style)]
        ]
        
        triage_table = Table(triage_data, colWidths=[481])
        triage_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor(bg_color)),
            ('BOX', (0,0), (-1,-1), 1.5, colors.HexColor(border_color)),
            ('PADDING', (0,0), (-1,-1), 8),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(triage_table)
        story.append(Spacer(1, 10))
        
        # --- SECTION 3: POSSIBLE DIAGNOSES ---
        diagnoses_title = "3. Possible Diagnoses" if language == "en" else "3. संभावित निदान"
        story.append(Paragraph(diagnoses_title, sec_title_style))
        
        diagnoses_list = report_data.get("diagnoses", [])
        
        diag_headers = [
            Paragraph(f"<b>{lbl['diagnosis']}</b>", meta_label_style),
            Paragraph(f"<b>{lbl['explanation']}</b>", meta_label_style),
            Paragraph(f"<b>{lbl['likelihood']}</b>", meta_label_style)
        ]
        
        diag_rows = [diag_headers]
        
        for diag in diagnoses_list:
            likelihood = diag.get("likelihood", "Low")
            if likelihood == "High":
                badge_bg = "#B91C1C"
            elif likelihood == "Moderate":
                badge_bg = "#C2410C"
            else: # Low
                badge_bg = "#0369A1"
                
            likelihood_html = f"<font color='{badge_bg}'><b>{likelihood}</b></font>"
            
            diag_rows.append([
                Paragraph(diag.get("name", ""), body_bold_style),
                Paragraph(diag.get("explanation", ""), body_style),
                Paragraph(likelihood_html, body_bold_style)
            ])
            
        diag_table = Table(diag_rows, colWidths=[140, 260, 81])
        diag_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#E2E8F0")),
            ('BOTTOMPADDING', (0,0), (-1,0), 6),
            ('TOPPADDING', (0,0), (-1,0), 6),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#F8FAFC")]),
            ('PADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(diag_table)
        story.append(Spacer(1, 10))
        
        # Let's add a PageBreak to keep the medication and interaction tables clean on page 2!
        story.append(PageBreak())
        
        # --- SECTION 4: SUGGESTED MEDICATIONS ---
        meds_section_title = "4. Suggested Medications" if language == "en" else "4. सुझाई गई दवाएं"
        story.append(Paragraph(meds_section_title, sec_title_style))
        
        suggested_meds = report_data.get("suggested_medications", [])
        
        med_headers = [
            Paragraph(f"<b>{lbl['drug']}</b>", meta_label_style),
            Paragraph(f"<b>{lbl['dosage']}</b>", meta_label_style),
            Paragraph(f"<b>{lbl['timing']}</b>", meta_label_style),
            Paragraph(f"<b>{lbl['duration_otc']}</b>", meta_label_style),
            Paragraph(f"<b>{lbl['warnings']}</b>", meta_label_style)
        ]
        
        med_rows = [med_headers]
        
        for med in suggested_meds:
            warnings_text = "<br/>".join([f"• {w}" for w in med.get("warnings", [])])
            
            med_cell = f"<b>{med.get('name')}</b><br/><font color='#64748B' size='8'>{med.get('generic_name')}</font>"
            dosage_cell = f"{med.get('dosage')}<br/>{med.get('frequency')}"
            timing_cell = f"{med.get('timing')}<br/>{med.get('meal_time')}"
            duration_cell = f"{med.get('duration')}<br/><b>{med.get('otc_or_rx')}</b>"
            
            med_rows.append([
                Paragraph(med_cell, body_style),
                Paragraph(dosage_cell, body_style),
                Paragraph(timing_cell, body_style),
                Paragraph(duration_cell, body_style),
                Paragraph(warnings_text, body_style)
            ])
            
        meds_table = Table(med_rows, colWidths=[110, 85, 95, 80, 111])
        meds_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#E2E8F0")),
            ('BOTTOMPADDING', (0,0), (-1,0), 6),
            ('TOPPADDING', (0,0), (-1,0), 6),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#F8FAFC")]),
            ('PADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(meds_table)
        story.append(Spacer(1, 10))
        
        # --- SECTION 5: DRUG INTERACTIONS ---
        interactions_title = "5. Drug Interaction Warnings" if language == "en" else "5. दवाओं के बीच परस्पर प्रभाव की चेतावनी (Drug Interaction)"
        story.append(Paragraph(interactions_title, sec_title_style))
        
        interactions_list = report_data.get("drug_interactions", [])
        
        if not interactions_list:
            no_int_text = "No severe drug interactions detected." if language == "en" else "दवाओं के बीच कोई गंभीर परस्पर प्रभाव (Interaction) नहीं पाया गया।"
            story.append(Paragraph(f"<font color='#16A34A'><b>✓ {no_int_text}</b></font>", body_bold_style))
            story.append(Spacer(1, 6))
        else:
            int_headers = [
                Paragraph(f"<b>{lbl['interaction']}</b>", meta_label_style),
                Paragraph(f"<b>{lbl['severity']}</b>", meta_label_style),
                Paragraph(f"<b>{lbl['description']}</b>", meta_label_style)
            ]
            
            int_rows = [int_headers]
            for inter in interactions_list:
                severity = inter.get("severity", "Minor")
                if severity == "Dangerous":
                    sev_color = "#DC2626"
                elif severity == "Moderate":
                    sev_color = "#EA580C"
                else:
                    sev_color = "#EAB308"
                    
                sev_html = f"<font color='{sev_color}'><b>{severity}</b></font>"
                
                int_rows.append([
                    Paragraph(f"<b>{inter.get('drug_a')}</b> ↔ <b>{inter.get('drug_b')}</b>", body_style),
                    Paragraph(sev_html, body_bold_style),
                    Paragraph(inter.get("description", ""), body_style)
                ])
                
            int_table = Table(int_rows, colWidths=[150, 80, 251])
            int_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#FEF2F2")),
                ('BOTTOMPADDING', (0,0), (-1,0), 6),
                ('TOPPADDING', (0,0), (-1,0), 6),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#FCA5A5")),
                ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#FEE2E2")),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#FFF5F5")]),
                ('PADDING', (0,0), (-1,-1), 6),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ]))
            story.append(int_table)
            story.append(Spacer(1, 10))
            
        # --- SECTION 6: ALLERGY FLAGS ---
        allergies_section_title = "6. Allergy Flags" if language == "en" else "6. एलर्जी चेतावनी (Allergy Flags)"
        story.append(Paragraph(allergies_section_title, sec_title_style))
        
        allergy_flags_list = report_data.get("allergy_flags", [])
        
        if not allergy_flags_list:
            no_all_text = "No allergy conflicts detected with suggested medications." if language == "en" else "सुझाई गई दवाओं के साथ एलर्जी का कोई टकराव नहीं पाया गया।"
            story.append(Paragraph(f"<font color='#16A34A'><b>✓ {no_all_text}</b></font>", body_bold_style))
            story.append(Spacer(1, 6))
        else:
            for flag in allergy_flags_list:
                flag_title = f"<b>{lbl['allergy_alert']}</b> {flag.get('drug')} ↔ {flag.get('allergen')}"
                flag_body = flag.get("description", "")
                
                flag_data = [[
                    Paragraph(f"<font color='#991B1B'>{flag_title}<br/>{flag_body}</font>", body_style)
                ]]
                flag_table = Table(flag_data, colWidths=[481])
                flag_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FEF2F2")),
                    ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#EF4444")),
                    ('PADDING', (0,0), (-1,-1), 6),
                ]))
                story.append(flag_table)
                story.append(Spacer(1, 6))
                
        story.append(Spacer(1, 4))
        
        # --- SECTION 7: GENERAL ADVICE ---
        advice_title = "7. General Advice & Supportive Care" if language == "en" else "7. सामान्य सलाह और सहायक देखभाल"
        story.append(Paragraph(advice_title, sec_title_style))
        
        advice_list = report_data.get("general_advice", [])
        for adv in advice_list:
            story.append(Paragraph(f"• {adv}", body_style))
            story.append(Spacer(1, 4))

        # Build PDF
        doc.build(story, canvasmaker=NumberedCanvas)
        
        buffer.seek(0)
        return buffer
